/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projetoec.view;

import br.inatel.projetoec.model.ArquivoIngrediente;
import br.inatel.projetoec.model.ArquivoLanche;
import br.inatel.projetoec.model.Ingrediente;
import br.inatel.projetoec.model.Lanche;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author aluno
 */
public class CadastroIngrediente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroIngrediente
     */
    public CadastroIngrediente() {
        initComponents();

        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/inatel/projetoec/imagens/images.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Ingrediente = new javax.swing.JPanel();
        txf_Nome = new javax.swing.JTextField();
        label_Nome = new javax.swing.JLabel();
        label_precoAdd = new javax.swing.JLabel();
        txf_precoAdd = new javax.swing.JTextField();
        label_titulo = new javax.swing.JLabel();
        btm_salvar = new javax.swing.JButton();
        btm_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        Painel_Ingrediente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        label_Nome.setText("NOME");

        label_precoAdd.setText("PREÇO ADICIONAL");

        txf_precoAdd.setText("0,00");

        label_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("INGREDIENTES");

        btm_salvar.setText("SALVAR");
        btm_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_salvarActionPerformed(evt);
            }
        });

        btm_cancelar.setText("CANCELAR");
        btm_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_IngredienteLayout = new javax.swing.GroupLayout(Painel_Ingrediente);
        Painel_Ingrediente.setLayout(Painel_IngredienteLayout);
        Painel_IngredienteLayout.setHorizontalGroup(
            Painel_IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_IngredienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_IngredienteLayout.createSequentialGroup()
                        .addGroup(Painel_IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_IngredienteLayout.createSequentialGroup()
                                .addComponent(label_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(label_precoAdd))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_IngredienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btm_cancelar)))
                        .addGap(18, 18, 18)
                        .addGroup(Painel_IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btm_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_precoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        Painel_IngredienteLayout.setVerticalGroup(
            Painel_IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_IngredienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(Painel_IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Nome)
                    .addComponent(txf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_precoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_precoAdd))
                .addGap(29, 29, 29)
                .addGroup(Painel_IngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_cancelar)
                    .addComponent(btm_salvar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Ingrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btm_cancelarActionPerformed

    private void btm_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_salvarActionPerformed
        try {
            String valor = txf_precoAdd.getText();
            valor = valor.replace(",", ".");
            //try c
            float adicional = (float) Double.parseDouble(valor);

            if (!txf_Nome.getText().equals("")) {

                if (adicional > 0) {
                    salvarIngrediente();
                    JOptionPane.showMessageDialog(rootPane, "SALVO COM SUCESSO",
                            "AVISO", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "PREÇO " + valor + " É INVALIDO",
                            "AVISO", JOptionPane.ERROR_MESSAGE);

                }
            } else {

                JOptionPane.showMessageDialog(rootPane, "CAMPO DE NOME VAZIO",
                        "AVISO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Preço Inválido", "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btm_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Ingrediente;
    private javax.swing.JButton btm_cancelar;
    private javax.swing.JButton btm_salvar;
    private javax.swing.JLabel label_Nome;
    private javax.swing.JLabel label_precoAdd;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JTextField txf_Nome;
    private javax.swing.JTextField txf_precoAdd;
    // End of variables declaration//GEN-END:variables

    private void salvarIngrediente() {

        ArquivoIngrediente i1 = new ArquivoIngrediente();

        ArrayList<Ingrediente> ingredientes = new ArrayList<>();

        ingredientes = i1.resgatarArquivo();
        Ingrediente in1 = new Ingrediente();

        in1.setNome(txf_Nome.getText());
        String valor = txf_precoAdd.getText();
        valor = valor.replace(",", ".");
        in1.setPrecoAdicional(Float.parseFloat(valor));

        ingredientes.add(in1);

        i1.salvarArquivo(ingredientes, false);

    }

}
